<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression><Authors>MoriTeahouse</Authors><Copyright>Copyright (c) 2026 MoriTeahouse</Copyright></PropertyGroup><ItemGroup><ProjectReference Include="../../lib/MatrixTea-Engine/src/MatrixTea.Engine.Packaging/MatrixTea.Engine.Packaging.csproj" /></ItemGroup></Project>
